{{- if and .Values.minio.createSecret (not .Values.minio.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.minio.secretName }}
  namespace: {{ include "k8s-s3-bucket-operator.namespace" . }}
  labels:
    {{- include "k8s-s3-bucket-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  MINIO_ENDPOINT: {{ .Values.minio.endpoint | quote }}
  MINIO_ACCESS_KEY: {{ .Values.minio.accessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.minio.secretKey | quote }}
  MINIO_USE_SSL: {{ .Values.minio.useSSL | quote }}
{{- end }}
