{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-s3-bucket-operator.serviceAccountName" . }}
  namespace: {{ include "k8s-s3-bucket-operator.namespace" . }}
  labels:
    {{- include "k8s-s3-bucket-operator.labels" . | nindent 4 }}
{{- end }}
